name: Install tools common to all our actions

runs:
  using: composite
  steps:
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: v1.7.1

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'yarn'

    - name: Install dependencies
      shell: bash
      run: yarn --frozen-lockfile --network-concurrency 1
