name: gas

on:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Run Gas Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: install-tools
        uses: ./.github/workflows/install-tools

      - name: Run Forge tests
        run: |
          FORGE_SNAPSHOT_CHECK=true FOUNDRY_NO_MATCH_TEST=DISABLE forge test --isolate --mt testGas -vvv
        id: test
        env:
          OPTIMISM_RPC_URL: ${{ secrets.OPTIMISM_RPC_URL }}
