name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit-tests:
    name: Hardhat Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: install-tools
        uses: ./.github/workflows/install-tools

      - name: Compile (generates typechain)
        run: yarn compile

      - name: Run hardhat tests
        run: yarn test:hardhat
        env:
          OPTIMISM_RPC_URL: ${{ secrets.OPTIMISM_RPC_URL }}
  test:
    name: Foundry Unit Tests
    runs-on: ubuntu-latest
    env:
      FOUNDRY_PROFILE: ci
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: install-tools
        uses: ./.github/workflows/install-tools

      - name: Run forge tests
        run: OUTPUT_FILENAME=Optimism.json CONSTANTS_FILENAME=Optimism.json yarn test:forge
        env:
          OPTIMISM_RPC_URL: ${{ secrets.OPTIMISM_RPC_URL }}
